broadcast:
  pre: '&9Автосохранение сервера'
  post: '&9Сохранение завершено'
broadcastbackup:
  pre: '&9Делаем автобэкап'
  post: '&9Автобэкап сделан'
broadcastpurge:
  pre: '&9Автоочистка сервера'
  post: '&9Очистка завершена'
warning:
  save: '&9Скоро начнётся автосохранение сервера'
  backup: '&9Скоро начнётся автобэкап сервера'
insufficentpermissions: '&9У вас нет доступа к этой команде'
autorestart:
  restarting: '&9Сервер перезагружается'
  countdown: '&9Сервер перезагрузится через {SECONDS} секунд'
worldregen:
  kickmessage: '&9Сервер регенерирует карту, вернитесь позже'
